apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-0pwbal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-0pwbal
  namespace: my-nginx-0pwbal
  labels:
    name: nginx-0pwbal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-0pwbal
  template:
    metadata:
      namespace: my-nginx-0pwbal
      labels:
        name: nginx-0pwbal
    spec:
      containers:
      - name: nginx-0pwbal
        image: nginx
        ports:
        - containerPort: 80

